on:
  pull_request:
    types: [review_requested, ready_for_review, closed]
  workflow_dispatch:

name: "Post on #trackydev"

jobs:
  post_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: trackyverse/action-otn-slack-post@c7cdb15c73f1eda16e45f1f2c80316024caedcfb
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
