on:
  pull_request:
    types: [review_requested, ready_for_review, closed]
  workflow_dispatch:

name: "Post on #trackydev"

jobs:
  post_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: trackyverse/action-otn-slack-post@d0482a50bd335417a67ba10bfc9f14ef3c0da1d4
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
